services:
  ui:
    image: mayanayza/netvisor-ui:latest
    volumes:
      - ui-build:/app/build

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: netvisor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    image: mayanayza/netvisor-server:latest
    ports:
      - "${NETVISOR_SERVER_PORT:-60072}:60072"
    environment:
      - NETVISOR_SERVER_PORT=${NETVISOR_SERVER_PORT:-60072}
      - NETVISOR_LOG_LEVEL=${NETVISOR_LOG_LEVEL:-info}
      - NETVISOR_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/netvisor
      - NETVISOR_WEB_EXTERNAL_PATH=${NETVISOR_WEB_EXTERNAL_PATH:-/app/static}
    volumes:
      - ./data:/data
      - ui-build:/app/static:ro
    depends_on:
      ui:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ui-build:
  postgres_data: