version: '3.8'

services:
  ui:
    image: mayanayza/netvisor-ui:latest
    volumes:
      - ui-build:/app/build

  server:
    image: mayanayza/netvisor-server:latest
    ports:
      - "60072:60072"
    environment:
      # Server configuration
      - NETVISOR_PORT=${NETVISOR_PORT:-60072}
      - NETVISOR_LOG_LEVEL=${NETVISOR_LOG_LEVEL:-info}
      - NETVISOR_DATABASE_PATH=${NETVISOR_DATABASE_PATH:-/data/netvisor.db}
      - NETVISOR_WEB_EXTERNAL_PATH=${NETVISOR_WEB_EXTERNAL_PATH:-/app/static}
    volumes:
      - ./data:/data
      - ui-build:/app/static:ro
    depends_on:
      - ui
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60072/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ui-build: