version: '3.8'

services:
  ui:
    build: 
      context: ../netvisor-ui
      dockerfile: Dockerfile.dev
    volumes:
      - ui-build:/app/build

  server:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "60072:60072"
    environment:
      - RUST_LOG=debug
      - NETVISOR_DATABASE_PATH=/data/netvisor.db
      - NETVISOR_WEB_EXTERNAL_PATH=/app/static
    volumes:
      - ./data:/data
      - ui-build:/app/static:ro
    depends_on:
      - ui
volumes:
  ui-build: