version: '3.8'

services:
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  server:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "60072:60072"
    environment:
      - RUST_LOG=debug
      - NETVISOR_DATABASE_PATH=/data/netvisor.db
      - NETVISOR_WEB_EXTERNAL_PATH=/app/static
    volumes:
      - ./server:/app
      - ./data:/data
      - ui-build:/app/static:ro
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/app/target
    depends_on:
      - ui

volumes:
  ui-build:
  cargo-cache:
  cargo-git:
  target-cache: