version: '3.8'

services:
  ui:
    image: mayanayza/netvisor-ui:latest
    volumes:
      - ui-build:/app/build

  server:
    image: mayanayza/netvisor-server:latest
    ports:
      - "60072:60072"
    environment:
      - RUST_LOG=info
      - NETVISOR_DATABASE_PATH=/data/netvisor.db
      - NETVISOR_WEB_EXTERNAL_PATH=/app/static
    volumes:
      - ./data:/data
      - ui-build:/app/static:ro
    depends_on:
      - ui
    command: sh -c "mkdir -p /data && touch /data/netvisor.db && chmod 755 /data && chmod 644 /data/netvisor.db && server"

volumes:
  ui-build: