# This is meant to be used on Linux hosts where --network host actually works

version: '3.8'

services:
  daemon:
    image: mayanayza/netvisor-daemon:latest
    container_name: netvisor-daemon
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      # Server connection
      - NETVISOR_SERVER_TARGET=${NETVISOR_SERVER_TARGET:-127.0.0.1}
      - NETVISOR_SERVER_PORT=${NETVISOR_SERVER_PORT:-60072}
      
      # Daemon configuration
      - NETVISOR_PORT=${NETVISOR_PORT:-60073}
      - NETVISOR_BIND_ADDRESS=${NETVISOR_BIND_ADDRESS:-0.0.0.0}
      - NETVISOR_NAME=${NETVISOR_NAME:-netvisor-daemon}
      - NETVISOR_LOG_LEVEL=${NETVISOR_LOG_LEVEL:-info}
      - NETVISOR_HEARTBEAT_INTERVAL=${NETVISOR_HEARTBEAT_INTERVAL:-30}
    volumes:
      # Persist daemon configuration and ID
      - daemon-config:/root/.config/netvisor/daemon
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60073/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  daemon-config: