name: Daemon CI

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/daemon-ci.yml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/daemon-ci.yml'

defaults:
  run:
    working-directory: ./server

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: server
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      
      - name: Check formatting
        run: cargo fmt -- --check
      
      - name: Clippy daemon
        run: cargo clippy --bin daemon --all-features -- -D warnings
      
      - name: Test daemon binary
        run: cargo test --bin daemon
      
      - name: Build daemon (release)
        run: cargo build --release --bin daemon

  docker-build-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build daemon Docker image (test)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile.daemon
          platforms: linux/amd64
          push: false
          load: true
          tags: netvisor-daemon:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test daemon container runs
        run: |
          docker run --rm netvisor-daemon:test netvisor-daemon --help
      
      - name: Test daemon container shows version info
        run: |
          docker run --rm netvisor-daemon:test netvisor-daemon --version || echo "Version flag not implemented yet"