build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build-binaries
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Get release version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Checkout UI repository
        uses: actions/checkout@v4
        with:
          repository: mayanayza/netvisor-ui
          path: netvisor-ui
      
      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./netvisor-ui
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mayanayza/netvisor-ui:${{ steps.version.outputs.version }}
            mayanayza/netvisor-ui:latest
      
      - name: Checkout Server repository
        uses: actions/checkout@v4
        with:
          repository: mayanayza/netvisor-server
          path: netvisor-server
      
      - name: Build and push Server image
        uses: docker/build-push-action@v5
        with:
          context: ./netvisor-server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mayanayza/netvisor-server:${{ steps.version.outputs.version }}
            mayanayza/netvisor-server:latest