name: Release

permissions:
  contents: write
  
on:
  release:
    types: [created]

jobs:
  build-binaries:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: netvisor-daemon-linux-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: netvisor-daemon-darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: netvisor-daemon-windows-x86_64.exe
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install OpenSSL (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      
      - name: Build
        run: cargo build --release --bin daemon --target ${{ matrix.target }}
      
      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cp target/${{ matrix.target }}/release/daemon ${{ matrix.binary }}
          chmod +x ${{ matrix.binary }}
      
      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cp target/${{ matrix.target }}/release/daemon.exe ${{ matrix.binary }}
      
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.binary }}